// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAcOgkyIK71jPUKBrUE9b5Njj6gydoFGPo',
    appId: '1:591579254309:web:9d72c00976d3f3eb2ff9cc',
    messagingSenderId: '591579254309',
    projectId: 'gla-certificate',
    authDomain: 'gla-certificate.firebaseapp.com',
    storageBucket: 'gla-certificate.appspot.com',
    measurementId: 'G-W9BSLYWW1P',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB4f9CwEHCXQcqWM-ExzhlLRMKS1PBwplo',
    appId: '1:591579254309:android:8c6c9c54a3542d5b2ff9cc',
    messagingSenderId: '591579254309',
    projectId: 'gla-certificate',
    storageBucket: 'gla-certificate.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDAf2J4tHygEVIv78ww1RLKoK6reUhy6Jw',
    appId: '1:591579254309:ios:9634bdcaf215775e2ff9cc',
    messagingSenderId: '591579254309',
    projectId: 'gla-certificate',
    storageBucket: 'gla-certificate.appspot.com',
    iosBundleId: 'com.example.glaCertificate',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDAf2J4tHygEVIv78ww1RLKoK6reUhy6Jw',
    appId: '1:591579254309:ios:9634bdcaf215775e2ff9cc',
    messagingSenderId: '591579254309',
    projectId: 'gla-certificate',
    storageBucket: 'gla-certificate.appspot.com',
    iosBundleId: 'com.example.glaCertificate',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAcOgkyIK71jPUKBrUE9b5Njj6gydoFGPo',
    appId: '1:591579254309:web:704f373d26d66b002ff9cc',
    messagingSenderId: '591579254309',
    projectId: 'gla-certificate',
    authDomain: 'gla-certificate.firebaseapp.com',
    storageBucket: 'gla-certificate.appspot.com',
    measurementId: 'G-WGQW7W6PFB',
  );
}
